import js from '@eslint/js';

const globals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  fetch: 'readonly',
  XMLHttpRequest: 'readonly',
  WebSocket: 'readonly',
  EventSource: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  KeyboardEvent: 'readonly',
  MouseEvent: 'readonly',
  TouchEvent: 'readonly',
  WheelEvent: 'readonly',
  DragEvent: 'readonly',
  PointerEvent: 'readonly',
  FocusEvent: 'readonly',
  InputEvent: 'readonly',
  ClipboardEvent: 'readonly',
  HTMLElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  HTMLTextAreaElement: 'readonly',
  HTMLSelectElement: 'readonly',
  HTMLFormElement: 'readonly',
  HTMLTableElement: 'readonly',
  HTMLDivElement: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  Text: 'readonly',
  DocumentFragment: 'readonly',
  SVGElement: 'readonly',
  FormData: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  Image: 'readonly',
  ImageData: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  IntersectionObserver: 'readonly',
  ResizeObserver: 'readonly',
  MutationObserver: 'readonly',
  matchMedia: 'readonly',
  getComputedStyle: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  performance: 'readonly',
  crypto: 'readonly',
  btoa: 'readonly',
  atob: 'readonly',
  structuredClone: 'readonly',
  queueMicrotask: 'readonly',
  DOMParser: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  console: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  visualViewport: 'readonly',
  indexedDB: 'readonly',
  Notification: 'readonly',
  XTerm: 'readonly',
  FitAddon: 'readonly',
  WebLinksAddon: 'readonly',
};

export default [
  js.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals,
    },
    rules: {
      'no-var': 'error',
      'prefer-const': 'error',
      'no-undef': 'error',
      'no-redeclare': 'off',
      'no-unused-vars': ['warn', { varsIgnorePattern: '^_', argsIgnorePattern: '^_|^e$|^evt$|^err$' }],
      semi: 'warn',
      eqeqeq: 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-fallthrough': 'warn',
      'no-empty': 'warn',
      indent: 'off',
    },
  },
];
